/* =====================================================================
   Static site assembler for crystalsellstoledo.com
   ---------------------------------------------------------------------
   Reads  : src/pages/*.html   (content + a JSON metadata header)
            src/partials/*.html (shared chrome)
   Writes : plain .html files at the repo root, ready for any static host.

   Run    : npm run build
   Why    : the header, footer and <head> are authored once. The output
            is still dependency-free HTML, so the deployed site needs no
            build step on the host.
   ===================================================================== */
import { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync } from "node:fs";
import { join, dirname, basename } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SITE = "https://www.crystalsellstoledo.com";

const partial = (name) => readFileSync(join(ROOT, "src/partials", name + ".html"), "utf8");
const PARTIALS = Object.fromEntries(
  readdirSync(join(ROOT, "src/partials"))
    .filter((f) => f.endsWith(".html"))
    .map((f) => [basename(f, ".html"), readFileSync(join(ROOT, "src/partials", f), "utf8")])
);

/** Replace {{> name }} includes and {{ var }} tokens, repeatedly, so
 *  partials may themselves contain includes and variables. */
function render(tpl, vars) {
  let out = tpl;
  for (let pass = 0; pass < 6; pass++) {
    const before = out;
    out = out.replace(/\{\{>\s*([\w-]+)\s*\}\}/g, (m, n) => {
      if (!(n in PARTIALS)) throw new Error(`Unknown partial: ${n}`);
      return PARTIALS[n];
    });
    out = out.replace(/\{\{\s*([\w.-]+)\s*\}\}/g, (m, k) =>
      Object.prototype.hasOwnProperty.call(vars, k) ? String(vars[k]) : ""
    );
    if (out === before) break;
  }
  return out;
}

/** Pages carry a JSON metadata block in a leading HTML comment. */
function parsePage(raw, file) {
  const m = raw.match(/^\s*<!--\s*meta\s*([\s\S]*?)-->\s*/);
  if (!m) throw new Error(`${file}: missing <!-- meta { ... } --> block`);
  let meta;
  try {
    meta = JSON.parse(m[1]);
  } catch (e) {
    throw new Error(`${file}: metadata is not valid JSON — ${e.message}`);
  }
  return { meta, body: raw.slice(m[0].length) };
}

const shell = partial("_shell");
const pagesDir = join(ROOT, "src/pages");
const built = [];

for (const file of readdirSync(pagesDir).filter((f) => f.endsWith(".html")).sort()) {
  const { meta, body } = parsePage(readFileSync(join(pagesDir, file), "utf8"), file);
  const slug = meta.slug ?? basename(file, ".html");
  const url = slug === "index" ? `${SITE}/` : `${SITE}/${slug}`;

  const vars = {
    title: meta.title,
    description: meta.description,
    canonical: url,
    ogImage: meta.ogImage ?? `${SITE}/assets/img/og-default.jpg`,
    bodyClass: meta.bodyClass ?? "",
    jsonld: meta.jsonld ? `\n<script type="application/ld+json">\n${JSON.stringify(meta.jsonld, null, 2)}\n</script>` : "",
    robots: meta.noindex ? '<meta name="robots" content="noindex, follow">' : "",
    nav_home: "", nav_sell: "", nav_buy: "", nav_hoods: "", nav_about: "", nav_contact: "",
    content: body.trim(),
  };
  if (meta.nav) vars["nav_" + meta.nav] = ' aria-current="page"';

  const banner = `<!-- Generated by tools/build.mjs from src/pages/${file} — edit the source, then run: npm run build -->\n`;
  const html = banner + render(shell, vars).replace(/\n{3,}/g, "\n\n");

  const outPath = join(ROOT, slug + ".html");
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, html);
  built.push({ slug, url, changefreq: meta.changefreq ?? "monthly", priority: meta.priority ?? 0.6, noindex: !!meta.noindex });
  console.log(`  ✓ ${slug}.html`);
}

/* ---- sitemap.xml ------------------------------------------------------ */
const today = new Date().toISOString().slice(0, 10);
const sitemap =
  `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
  built
    .filter((p) => !p.noindex)
    .map((p) => `  <url>\n    <loc>${p.url}</loc>\n    <lastmod>${today}</lastmod>\n    <changefreq>${p.changefreq}</changefreq>\n    <priority>${p.priority}</priority>\n  </url>`)
    .join("\n") +
  `\n</urlset>\n`;
writeFileSync(join(ROOT, "sitemap.xml"), sitemap);
console.log(`  ✓ sitemap.xml (${built.filter((p) => !p.noindex).length} urls)`);
console.log(`\nBuilt ${built.length} pages.`);
